name: Ruby

env:
  RUBY_VERSION: 2.5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install Rubocop
        run: |
          gem install --no-doc rubocop
          gem install --no-doc rubocop-rails
          gem install --no-doc rubocop-performance

      - name: Check code
        run: rubocop

  rspec:
    needs: rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Cache ruby gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          gem install bundler --no-doc
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: COVERAGE=true bundle exec rake test

      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
